### ISSUE TITLE
Its Not Work For Me Again :(

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentXMRMiner#249] opened 2021-05-09 15:59 UTC
I Tested In My Computer But Not Work

**Comment by DogusCyk** [comment] 2021-05-09 16:01
Im Sending Video

**Comment by DogusCyk** [comment] 2021-05-09 16:06
[Yeni klasör (2).zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6447945/Yeni.klasor.2.zip)

**Comment by DogusCyk** [comment] 2021-05-09 16:15
Man I Opening So Fast Task Manager I Need Saw Like Sec

**Comment by DogusCyk** [comment] 2021-05-09 16:15
Its Not Work

**Comment by DogusCyk** [comment] 2021-05-09 16:15
Also I Need Saw 2 Explorer And Its Using 2GB RAM

**Comment by UnamSanctam** [comment] 2021-05-09 16:15
Task Manager has a slow default update rate, disable 'Stealth' and run it and check it that way.

**Comment by UnamSanctam** [comment] 2021-05-09 16:16
If it's using 2GB of ram then it's working.

**Comment by DogusCyk** [comment] 2021-05-09 16:17
Okey Im Going Close Stealth And Test Again

**Comment by DogusCyk** [comment] 2021-05-09 16:23
[2021-05-09 19-17-58.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6447981/2021-05-09.19-17-58.zip)

**Comment by DogusCyk** [comment] 2021-05-09 16:25
Not Work

**Comment by UnamSanctam** [comment] 2021-05-09 16:28
It does but you have 'Stealth' enabled so you probably miss it.

**Comment by DogusCyk** [comment] 2021-05-09 16:29
> It does but you have 'Stealth' enabled so you probably miss it.

U Didnt Watch Video ? I Close Stealth And Build Again

**Comment by DogusCyk** [comment] 2021-05-09 16:29
Its Not Work 😳

**Comment by DogusCyk** [comment] 2021-05-09 16:32
WHY

**Comment by UnamSanctam** [comment] 2021-05-09 16:32
You should search for the miner (explorer.exe or whatever you chose) by searching for --url in the top right search box.

**Comment by UnamSanctam** [comment] 2021-05-09 16:33
Decrease the 'Start Delay' to 1 second since you have it set to 30 seconds and have to wait for it to start then.

**Comment by DogusCyk** [comment] 2021-05-09 16:34
[2021-05-09 19-33-05.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448003/2021-05-09.19-33-05.zip)

**Comment by DogusCyk** [comment] 2021-05-09 16:36
whats wrong

**Comment by UnamSanctam** [comment] 2021-05-09 16:37
Nothing is wrong, it should close down after it has injected the miner into explorer.exe (or whatever you chose in the 'Inject Into' option). The miner should show up as explorer.exe.

**Comment by DogusCyk** [comment] 2021-05-09 16:41
> Nothing is wrong, it should close down after it has injected the miner into explorer.exe (or whatever you chose in the 'Inject Into' option). The miner should show up as explorer.exe.

man its not use my cpu ...

**Comment by DogusCyk** [comment] 2021-05-09 16:41
there is no explorer or not miner

**Comment by UnamSanctam** [comment] 2021-05-09 16:44
Just open up Process Hacker and search for --url in the search box where you searched for sihost64 and see if anything comes up.

It won't use your CPU if you haven't closed down the old miner that has 'Stealth' enabled. Run the uninstaller that should be created in the same folder as the miner if you want it to automatically close it down.

**Comment by DogusCyk** [comment] 2021-05-09 17:01
rip i dont understand anything i did open uninstaller then build again but its too not work 😢

**Comment by UnamSanctam** [comment] 2021-05-09 17:03
If you search for --url in the search box does anything show up? If it doesn't then just start the miner without the 'Stealth' enabled and see if it shows up then.

**Comment by DogusCyk** [comment] 2021-05-09 17:03
okey let me try

**Comment by DogusCyk** [comment] 2021-05-09 17:06
![image](https://user-images.githubusercontent.com/81167210/117580735-18db2c80-b102-11eb-8f7e-8896770bdb67.png)

**Comment by DogusCyk** [comment] 2021-05-09 17:07
i did open stealth

**Comment by DogusCyk** [comment] 2021-05-09 17:07
Startup Added But Miner Its Not Work Or Im Dumb 😳

**Comment by UnamSanctam** [comment] 2021-05-09 17:08
Send the miner without 'Stealth' here. It should show up there in that list after the 'Start Delay' has passed.

**Comment by DogusCyk** [comment] 2021-05-09 17:08
![image](https://user-images.githubusercontent.com/81167210/117580783-488a3480-b102-11eb-903b-75f2ca499949.png)
![image](https://user-images.githubusercontent.com/81167210/117580790-55a72380-b102-11eb-8771-524d54af87ab.png)

**Comment by DogusCyk** [comment] 2021-05-09 17:09
[TESTUNAMAGAIN.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448058/TESTUNAMAGAIN.zip)

**Comment by DogusCyk** [comment] 2021-05-09 17:09
i open stealth and start delay 30

**Comment by DogusCyk** [comment] 2021-05-09 17:09
if im doing wrong sorry my english sucks 😢

**Comment by UnamSanctam** [comment] 2021-05-09 17:14
It's all working for me, explorer does start and all is correct although that miner has 'Stealth' enabled so it doesn't show any CPU.
<img width="319" alt="4a031a90c41d8ea5d527" src="https://user-images.githubusercontent.com/10323655/117580987-b894bc80-b0fa-11eb-9105-69a656c8af45.png">

**Comment by DogusCyk** [comment] 2021-05-09 17:15
also i have 1 explorer in process hacker you have 2 ?

**Comment by DogusCyk** [comment] 2021-05-09 17:16
![image](https://user-images.githubusercontent.com/81167210/117581037-6ad08200-b103-11eb-821b-854fc4909fde.png)

**Comment by UnamSanctam** [comment] 2021-05-09 17:16
Yes, try changing the 'Inject Into' option to something like nslookup and then just search for nslookup in Process Hacker and wait for the miner to start. Since you have 'Install' enabled it should take 1 minute (2 * 'Start Delay') for it to start.

**Comment by DogusCyk** [comment] 2021-05-09 17:17
let me build again start delay 1

**Comment by DogusCyk** [comment] 2021-05-09 17:19
![image](https://user-images.githubusercontent.com/81167210/117581110-d87cae00-b103-11eb-93f6-7ae86554c4f9.png)
![image](https://user-images.githubusercontent.com/81167210/117581114-e03c5280-b103-11eb-80b2-7c72ee4d6556.png)

**Comment by DogusCyk** [comment] 2021-05-09 17:21
im checking moneroocean too but there is not my miner

**Comment by UnamSanctam** [comment] 2021-05-09 17:22
Here, try starting this and see if it shows up.
[TEST.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448087/TEST.zip)

**Comment by DogusCyk** [comment] 2021-05-09 17:22
i open and search for --url ?

**Comment by UnamSanctam** [comment] 2021-05-09 17:22
Yes do that.

**Comment by DogusCyk** [comment] 2021-05-09 17:23
![image](https://user-images.githubusercontent.com/81167210/117581226-740e1e80-b104-11eb-8d34-e9988288372d.png)

**Comment by DogusCyk** [comment] 2021-05-09 17:23
now its close

**Comment by UnamSanctam** [comment] 2021-05-09 17:26
Then possibly your computer does not support something. Try extracting both files from the following .zip to a folder and start the start.bat.
[TEST.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448102/TEST.zip)

**Comment by DogusCyk** [comment] 2021-05-09 17:27
okey

**Comment by DogusCyk** [comment] 2021-05-09 17:28
![image](https://user-images.githubusercontent.com/81167210/117581380-17f7ca00-b105-11eb-83d1-c605bc2150b9.png)

**Comment by DogusCyk** [comment] 2021-05-09 17:29
its work ?

**Comment by UnamSanctam** [comment] 2021-05-09 17:29
So the miner does seem to work, seems like something closes the injected miner down on your computer. Do you have some sort of antivirus that closes it down?

**Comment by DogusCyk** [comment] 2021-05-09 17:30
i have just windows defender but its too close.

**Comment by DogusCyk** [comment] 2021-05-09 17:30
i close with defender control

**Comment by DogusCyk** [comment] 2021-05-09 17:30
maybe its block me again ?

**Comment by DogusCyk** [comment] 2021-05-09 17:34
i test this ?

**Comment by UnamSanctam** [comment] 2021-05-09 17:34
Yes do that same thing as the last file I sent, start the start.bat and a console should show up.

**Comment by DogusCyk** [comment] 2021-05-09 17:34
![image](https://user-images.githubusercontent.com/81167210/117581548-fb0fc680-b105-11eb-83dc-ff5aebff37ae.png)

**Comment by UnamSanctam** [comment] 2021-05-09 17:37
Yes just wait for a bit, is it possible for you to open the example config https://pastebin.com/raw/jJVATHzg or is that blocked?

**Comment by DogusCyk** [comment] 2021-05-09 17:38
im waiting but nothing happen

**Comment by DogusCyk** [comment] 2021-05-09 17:39
![image](https://user-images.githubusercontent.com/81167210/117581636-9a34be00-b106-11eb-8674-dbb5c9d21fd3.png)

**Comment by DogusCyk** [comment] 2021-05-09 17:39
![image](https://user-images.githubusercontent.com/81167210/117581645-a587e980-b106-11eb-9ce1-ae704b856df1.png)

**Comment by DogusCyk** [comment] 2021-05-09 17:39
![image](https://user-images.githubusercontent.com/81167210/117581648-ac166100-b106-11eb-8c30-3fc1937118c1.png)

**Comment by UnamSanctam** [comment] 2021-05-09 17:40
Hmm interesting, seems like it might crash because Turkey blocks pastebin.

**Comment by DogusCyk** [comment] 2021-05-09 17:41
yes i cant go pastebin i need open vpn

**Comment by UnamSanctam** [comment] 2021-05-09 17:42
If you have a VPN could you try and connect to a country that doesn't block pastebin and then start the latest start.bat again?

**Comment by DogusCyk** [comment] 2021-05-09 17:42
okey

**Comment by DogusCyk** [comment] 2021-05-09 17:43
![image](https://user-images.githubusercontent.com/81167210/117581783-41b1f080-b107-11eb-8cb7-86e9f5a144de.png)

**Comment by DogusCyk** [comment] 2021-05-09 17:44
i open vpn and open again but

**Comment by UnamSanctam** [comment] 2021-05-09 17:44
And it's possible to open https://pastebin.com/raw/jJVATHzg?

**Comment by DogusCyk** [comment] 2021-05-09 17:45
![image](https://user-images.githubusercontent.com/81167210/117581818-732abc00-b107-11eb-8253-334aa4096111.png)


> And it's possible to open https://pastebin.com/raw/jJVATHzg?

**Comment by DogusCyk** [comment] 2021-05-09 17:45
no cant

**Comment by UnamSanctam** [comment] 2021-05-09 17:47
Ah, could you try another country that allows pastebin then? There might also be a setting in your VPN that you might have to enable to bypass government blocks as well.

**Comment by DogusCyk** [comment] 2021-05-09 17:48
![image](https://user-images.githubusercontent.com/81167210/117581870-d7e61680-b107-11eb-9cc4-1c78108e51a5.png)

**Comment by DogusCyk** [comment] 2021-05-09 17:48
i can open with vpn so what i do now

**Comment by UnamSanctam** [comment] 2021-05-09 17:48
Ok nice, could you test the start.bat now?

**Comment by DogusCyk** [comment] 2021-05-09 17:48
okey

**Comment by DogusCyk** [comment] 2021-05-09 17:49
![image](https://user-images.githubusercontent.com/81167210/117581893-006e1080-b108-11eb-8056-5ef16f28850c.png)

**Comment by DogusCyk** [comment] 2021-05-09 17:49
![Uploading image.png…]()

**Comment by DogusCyk** [comment] 2021-05-09 17:49
its like work with vpn

**Comment by UnamSanctam** [comment] 2021-05-09 17:50
Ok so it seems like the block causes it to crash. Seems very weird since if I use a Turkish VPN and it's blocked then it still works for me.

**Comment by DogusCyk** [comment] 2021-05-09 17:50
so weird

**Comment by DogusCyk** [comment] 2021-05-09 17:50
so what we do now 👍

**Comment by UnamSanctam** [comment] 2021-05-09 17:56
Turn off your VPN and please test this new version.
[testcustom2.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448130/testcustom2.zip)

**Comment by DogusCyk** [comment] 2021-05-09 17:57
okey

**Comment by DogusCyk** [comment] 2021-05-09 17:57
![image](https://user-images.githubusercontent.com/81167210/117582140-38c21e80-b109-11eb-8976-ff115e3ec96e.png)

**Comment by DogusCyk** [comment] 2021-05-09 17:58
start.cmd ?

**Comment by UnamSanctam** [comment] 2021-05-09 17:58
Yes, don't forget to extract them to a folder first.

**Comment by DogusCyk** [comment] 2021-05-09 17:58
i did but

**Comment by DogusCyk** [comment] 2021-05-09 17:58
owh wait

**Comment by DogusCyk** [comment] 2021-05-09 17:59
![image](https://user-images.githubusercontent.com/81167210/117582173-69a25380-b109-11eb-9217-ab35053939f2.png)

**Comment by DogusCyk** [comment] 2021-05-09 18:00
its too blocked i think

**Comment by UnamSanctam** [comment] 2021-05-09 18:01
Yes it should be, but wait for a bit and see if it crashes or not.

**Comment by DogusCyk** [comment] 2021-05-09 18:01
sure

**Comment by DogusCyk** [comment] 2021-05-09 18:02
![image](https://user-images.githubusercontent.com/81167210/117582266-de758d80-b109-11eb-8e4b-868014688262.png)

**Comment by UnamSanctam** [comment] 2021-05-09 18:04
Really weird, it seems to crash before the connection even finishes. And the same doesn't happen for me if I use a Turkish VPN.

**Comment by DogusCyk** [comment] 2021-05-09 18:05
👍

**Comment by DogusCyk** [comment] 2021-05-09 18:05
but old version work for me

**Comment by DogusCyk** [comment] 2021-05-09 18:05
maybe 🤣

**Comment by UnamSanctam** [comment] 2021-05-09 18:06
Yeah which is weird since the code is nearly identical. I'll try and update the http library and see if that changes anything.

**Comment by DogusCyk** [comment] 2021-05-09 18:06
okey thanks for your helps ❤️

**Comment by DogusCyk** [comment] 2021-05-09 18:07
can we tomorrow continue im so busy

**Comment by UnamSanctam** [comment] 2021-05-09 18:08
Yes sure, If you could test this final one I'd be thankful
[testcustom3.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448154/testcustom3.zip)

**Comment by DogusCyk** [comment] 2021-05-09 18:08
okey

**Comment by DogusCyk** [comment] 2021-05-09 18:08
i can wait like 20-30 min later more

**Comment by DogusCyk** [comment] 2021-05-09 18:09
i think its too not work nothing happen again
![image](https://user-images.githubusercontent.com/81167210/117582466-ceaa7900-b10a-11eb-8ecd-bee525e5f787.png)

**Comment by DogusCyk** [comment] 2021-05-09 18:09
lets wait

**Comment by DogusCyk** [comment] 2021-05-09 18:09
![image](https://user-images.githubusercontent.com/81167210/117582493-e7b32a00-b10a-11eb-9852-a65262127a24.png)

**Comment by DogusCyk** [comment] 2021-05-09 18:10
and crash

**Comment by UnamSanctam** [comment] 2021-05-09 18:11
Yeah, thanks for testing it. I'll try to make it crash on my computer to see if I can find the error so you can go if you have something to do.

**Comment by DogusCyk** [comment] 2021-05-09 18:11
okey if u find i can check thanks for your helps ❤️

**Comment by UnamSanctam** [comment] 2021-05-09 19:44
I believe I have solved the issue, when you get back and have the time could you test run this and see if it crashes for you?
[testcustom4.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448274/testcustom4.zip)

**Comment by DogusCyk** [comment] 2021-05-09 20:02
> I believe I have solved the issue, when you get back and have the time could you test run this and see if it crashes for you?
> [testcustom4.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448274/testcustom4.zip)

can wait like 10 15 min ill test :)

**Comment by DogusCyk** [comment] 2021-05-09 20:13
![image](https://user-images.githubusercontent.com/81167210/117585650-34ebc780-b11c-11eb-916f-3e2ec20e9011.png)

**Comment by DogusCyk** [comment] 2021-05-09 20:14
rip its too going crash 😢

**Comment by DogusCyk** [comment] 2021-05-09 20:14
![image](https://user-images.githubusercontent.com/81167210/117585674-577de080-b11c-11eb-8d1d-c01cdf139001.png)

**Comment by DogusCyk** [comment] 2021-05-09 20:14
WAIT its work ?

**Comment by UnamSanctam** [comment] 2021-05-09 20:15
Ah great!

**Comment by DogusCyk** [comment] 2021-05-09 20:15
![image](https://user-images.githubusercontent.com/81167210/117585690-695f8380-b11c-11eb-9b9b-28be26d63456.png)

**Comment by DogusCyk** [comment] 2021-05-09 20:15
Nice Job man !

**Comment by DogusCyk** [comment] 2021-05-09 20:15
thank you so much ❤️

**Comment by UnamSanctam** [comment] 2021-05-09 20:15
Yeah it seems to work. I'll update the builder. And thank you for all the help with testing

**Comment by DogusCyk** [comment] 2021-05-09 20:16
> Yeah it seems to work. I'll update the builder. And thank you for all the help with testing

Thanks Man ❤️

**Comment by DogusCyk** [comment] 2021-05-09 20:18
im waiting for update

**Comment by UnamSanctam** [comment] 2021-05-09 20:48
Had to test it a bit to test if the 'Remote Configuration' option worked as well since it uses similar code and it looks like everything works so I've uploaded the new version now https://github.com/UnamSanctam/SilentXMRMiner/releases.

**Comment by DogusCyk** [comment] 2021-05-09 20:55
ill check like 10 min later

**Comment by DogusCyk** [comment] 2021-05-09 20:56
should i open windows defender killer ?
but im puting file .rar

**Comment by UnamSanctam** [comment] 2021-05-09 20:57
Don't enable "Kill" Windows Defender when you're just testing, only do it when you're going to release it.

**Comment by DogusCyk** [comment] 2021-05-09 20:58
so if i test dont open right ?

**Comment by UnamSanctam** [comment] 2021-05-09 20:58
Yes

**Comment by DogusCyk** [comment] 2021-05-09 20:58
but i puting file in rar if normal open mining start ?

**Comment by DogusCyk** [comment] 2021-05-09 20:59
or no

**Comment by DogusCyk** [comment] 2021-05-09 20:59
if he open in rar mining start ?

**Comment by UnamSanctam** [comment] 2021-05-09 21:00
What exactly do you mean?

**Comment by DogusCyk** [comment] 2021-05-09 21:00
Im Puting File in rar

**Comment by DogusCyk** [comment] 2021-05-09 21:01
sorry for bad english

**Comment by DogusCyk** [comment] 2021-05-09 21:01
if he open in rar miner start ?

**Comment by UnamSanctam** [comment] 2021-05-09 21:02
Ah, it will start if he opens it inside the RAR if that's what you mean, and yes enable "Kill" Windows Defender for the file you're going to send to others.

**Comment by DogusCyk** [comment] 2021-05-09 21:03
so if he open in inside the rar Kill windows defender work ?

**Comment by DogusCyk** [comment] 2021-05-09 21:03
🤣

**Comment by DogusCyk** [comment] 2021-05-09 21:04
also now stealth its not show cpu using ?

**Comment by UnamSanctam** [comment] 2021-05-09 21:05
Yes it will work even if he opens it inside the RAR file. And yes if 'Stealth' is enabled it will not show any CPU usage when Task Manager or Process Hacker is open.

**Comment by DogusCyk** [comment] 2021-05-09 21:05
how can i correct for work with stealth ?

**Comment by UnamSanctam** [comment] 2021-05-09 21:07
Do you mean how to check if it works? Disable 'Stealth' and test that one like you did before.

**Comment by DogusCyk** [comment] 2021-05-09 21:08
okey thanks for helps ❤️

**Comment by DogusCyk** [comment] 2021-05-09 21:11
i close stealth and build but not work or im doing something wrong

**Comment by DogusCyk** [comment] 2021-05-09 21:11
let me wait

**Comment by DogusCyk** [comment] 2021-05-09 21:14
![image](https://user-images.githubusercontent.com/81167210/117587048-a92a6900-b124-11eb-98a9-981ae0203208.png)

**Comment by UnamSanctam** [comment] 2021-05-09 21:15
Test this, it should come up after 15 seconds.
[TEST.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448433/TEST.zip)

**Comment by DogusCyk** [comment] 2021-05-09 21:15
okey

**Comment by DogusCyk** [comment] 2021-05-09 21:16
i open and search for --url ?

**Comment by UnamSanctam** [comment] 2021-05-09 21:16
Yeah

**Comment by DogusCyk** [comment] 2021-05-09 21:16
![image](https://user-images.githubusercontent.com/81167210/117587117-00c8d480-b125-11eb-9f9e-1fa34069b79d.png)

**Comment by DogusCyk** [comment] 2021-05-09 21:17
its work but my miner not work

**Comment by DogusCyk** [comment] 2021-05-09 21:17
weird did u update link ?

**Comment by DogusCyk** [comment] 2021-05-09 21:17
> Test this, it should come up after 15 seconds.
> [TEST.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448433/TEST.zip)

also did u open stealth in this miner ?

**Comment by UnamSanctam** [comment] 2021-05-09 21:17
Yeah, I built that one with the one I just downloaded for the releases page.

**Comment by DogusCyk** [comment] 2021-05-09 21:18
> Yeah, I built that one with the one I just downloaded for the releases page.
let me build another one with no stealth

**Comment by DogusCyk** [comment] 2021-05-09 21:20
before i open stealth and tested now i close maybe old miner work ?

**Comment by UnamSanctam** [comment] 2021-05-09 21:21
Test this one, I built this one with the newest release with just nanopool, the wallet address and SSL/TLS, nothing more.
[TEST2.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448440/TEST2.zip)

**Comment by DogusCyk** [comment] 2021-05-09 21:21
![image](https://user-images.githubusercontent.com/81167210/117587274-b3009c00-b125-11eb-9c20-6ed281e98632.png)

**Comment by DogusCyk** [comment] 2021-05-09 21:22
also my watchdog too cant activated

**Comment by DogusCyk** [comment] 2021-05-09 21:22
> Test this one, I built this one with the newest release with just nanopool, the wallet address and SSL/TLS, nothing more.
> [TEST2.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448440/TEST2.zip)

okey

**Comment by DogusCyk** [comment] 2021-05-09 21:22
![image](https://user-images.githubusercontent.com/81167210/117587292-dcb9c300-b125-11eb-8e6a-9f5ca4b78b4a.png)

**Comment by DogusCyk** [comment] 2021-05-09 21:23
its work

**Comment by DogusCyk** [comment] 2021-05-09 21:23
but its not use cpu ?

**Comment by DogusCyk** [comment] 2021-05-09 21:23
owh sorry its useing now

**Comment by DogusCyk** [comment] 2021-05-09 21:24
but my miner why its not work

**Comment by UnamSanctam** [comment] 2021-05-09 21:24
Redownload the builder from the releases page and record when you build it.

**Comment by DogusCyk** [comment] 2021-05-09 21:24
okey

**Comment by DogusCyk** [comment] 2021-05-09 21:28
[2021-05-10 00-25-21.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6448453/2021-05-10.00-25-21.zip)

**Comment by UnamSanctam** [comment] 2021-05-09 21:31
Could you enable 'DEBUG' in the 'Advanced Options' and see if you get any error messages when you run the miner?

**Comment by DogusCyk** [comment] 2021-05-09 21:32
okey

**Comment by DogusCyk** [comment] 2021-05-09 21:33
![image](https://user-images.githubusercontent.com/81167210/117587584-64540180-b127-11eb-8361-a1bd0ffeefe0.png)

**Comment by DogusCyk** [comment] 2021-05-09 21:36
![image](https://user-images.githubusercontent.com/81167210/117587666-bf85f400-b127-11eb-973f-bd92275acb1e.png)

**Comment by DogusCyk** [comment] 2021-05-09 21:38
i need close my computer lets we continue tomorrow sorry 😢

**Comment by DogusCyk** [comment] 2021-05-09 21:38
when im back ill message this issue

**Comment by DogusCyk** [comment] 2021-05-09 21:38
like 12 - 13 hours later

**Comment by UnamSanctam** [comment] 2021-05-09 21:39
Yeah, it seems like it cannot embed the DLLs, you should probably build it in another folder but you can do that later. See you later :)

**Comment by DogusCyk** [comment] 2021-05-09 21:39
Good night ❤️

**Comment by DogusCyk** [comment] 2021-05-10 08:46
yo im back so i need build in new folder ?

**Comment by DogusCyk** [comment] 2021-05-10 08:51
![image](https://user-images.githubusercontent.com/81167210/117632665-ff7bc400-b185-11eb-9d79-910afee6ff9b.png)

**Comment by DogusCyk** [comment] 2021-05-10 08:51
![image](https://user-images.githubusercontent.com/81167210/117632759-128e9400-b186-11eb-97d6-4579c41ff9eb.png)

**Comment by DogusCyk** [comment] 2021-05-10 08:54
miner start but not injecting

**Comment by UnamSanctam** [comment] 2021-05-10 09:00
Yeah that looks like the miner isn't created properly, if you enable 'Pause for Obfuscation' can you send the DLL that gets created here?

**Comment by DogusCyk** [comment] 2021-05-10 09:02
i didnt enable pause for obuscation

**Comment by DogusCyk** [comment] 2021-05-10 09:02
what do i now 🤣

**Comment by UnamSanctam** [comment] 2021-05-10 09:05
Yes, then I should be able to look at it.

**Comment by DogusCyk** [comment] 2021-05-10 09:06
![image](https://user-images.githubusercontent.com/81167210/117634904-0d324900-b188-11eb-9249-34de995749b9.png)
![image](https://user-images.githubusercontent.com/81167210/117634927-128f9380-b188-11eb-8153-1d0e5c99cef8.png)
![image](https://user-images.githubusercontent.com/81167210/117634957-18857480-b188-11eb-958b-a3565698f7b0.png)

**Comment by DogusCyk** [comment] 2021-05-10 09:06
![image](https://user-images.githubusercontent.com/81167210/117635018-26d39080-b188-11eb-9b2b-dc24bda63835.png)

**Comment by DogusCyk** [comment] 2021-05-10 09:06
i didnt get any dll ?

**Comment by UnamSanctam** [comment] 2021-05-10 09:07
Don't press OK on the message boxes, when you do it will embed the DLL into the miner.

**Comment by DogusCyk** [comment] 2021-05-10 09:07
owh okey

**Comment by DogusCyk** [comment] 2021-05-10 09:09
[TESTINGDLL-watchdog.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6450929/TESTINGDLL-watchdog.zip)

**Comment by UnamSanctam** [comment] 2021-05-10 09:48
Could you try and start the builder as administrator?

**Comment by DogusCyk** [comment] 2021-05-10 11:50
okey

**Comment by DogusCyk** [comment] 2021-05-10 11:52
![image](https://user-images.githubusercontent.com/81167210/117655174-678ad400-b19f-11eb-9a19-598564f0c3c3.png)

**Comment by DogusCyk** [comment] 2021-05-10 11:53
nothing change

**Comment by UnamSanctam** [comment] 2021-05-10 11:53
Start the miner as administrator as well and enable DEBUG. Your error looks like it says that access is denied.

**Comment by DogusCyk** [comment] 2021-05-10 11:54
okey

**Comment by DogusCyk** [comment] 2021-05-10 11:54
![image](https://user-images.githubusercontent.com/81167210/117655338-9a34cc80-b19f-11eb-99b9-a8a1cf529573.png)

**Comment by DogusCyk** [comment] 2021-05-10 11:54
i enable this or opening admin ?

**Comment by UnamSanctam** [comment] 2021-05-10 11:55
Enable 'Run as Administrator' and DEBUG.

**Comment by DogusCyk** [comment] 2021-05-10 11:55
okey

**Comment by DogusCyk** [comment] 2021-05-10 11:58
![image](https://user-images.githubusercontent.com/81167210/117655688-15967e00-b1a0-11eb-9c49-ab38d078b100.png)
![image](https://user-images.githubusercontent.com/81167210/117655719-1deeb900-b1a0-11eb-8ba6-d31b49efb91a.png)

**Comment by DogusCyk** [comment] 2021-05-10 12:00
also if i open uninstaller

**Comment by DogusCyk** [comment] 2021-05-10 12:00
i got this

**Comment by DogusCyk** [comment] 2021-05-10 12:00
![image](https://user-images.githubusercontent.com/81167210/117656043-8178e680-b1a0-11eb-86a9-1e1505168839.png)

**Comment by DogusCyk** [comment] 2021-05-10 12:03
why my miner not work

**Comment by UnamSanctam** [comment] 2021-05-10 12:08
You should try building it on another computer if you have one, it seems like something goes wrong when you compile it.

**Comment by DogusCyk** [comment] 2021-05-10 12:08
i dont have 😢

**Comment by DogusCyk** [comment] 2021-05-10 12:10
maybe its work

**Comment by DogusCyk** [comment] 2021-05-10 12:13
> Possibly since it doesn't use any loaders but if you compile a miner without Watchdog on the newest version does it work?

i dont know how i can check ?

**Comment by DogusCyk** [comment] 2021-05-10 12:13
so i dont open watchdog in newest version ?

**Comment by UnamSanctam** [comment] 2021-05-10 12:14
Build a miner without watchdog or 'Install' enabled.

**Comment by DogusCyk** [comment] 2021-05-10 12:14
> Build a miner without watchdog or 'Install' enabled.

i always opening install and watchdog

**Comment by DogusCyk** [comment] 2021-05-10 12:15
![image](https://user-images.githubusercontent.com/81167210/117657678-85a60380-b1a2-11eb-88bd-9c9fb5dfd4ef.png)

**Comment by UnamSanctam** [comment] 2021-05-10 12:15
Yes but why not try without it? If it works without it you would know what the issue is.

**Comment by DogusCyk** [comment] 2021-05-10 12:15
![image](https://user-images.githubusercontent.com/81167210/117657747-9b1b2d80-b1a2-11eb-8a9a-67595918784a.png)

**Comment by DogusCyk** [comment] 2021-05-10 12:15
no its useing

**Comment by DogusCyk** [comment] 2021-05-10 12:17
so i build in new version with no watchdog ?

**Comment by UnamSanctam** [comment] 2021-05-10 12:17
Yeah, try to compile the new version with just pool address, wallet address.

**Comment by DogusCyk** [comment] 2021-05-10 12:18
okey

**Comment by DogusCyk** [comment] 2021-05-10 12:20
![image](https://user-images.githubusercontent.com/81167210/117658261-34e2da80-b1a3-11eb-8ddf-e9f673376968.png)

**Comment by DogusCyk** [comment] 2021-05-10 12:20
![image](https://user-images.githubusercontent.com/81167210/117658343-4af09b00-b1a3-11eb-9983-6468b3cd421c.png)

**Comment by DogusCyk** [comment] 2021-05-10 12:20
its work but

**Comment by DogusCyk** [comment] 2021-05-10 12:21
its easy to find and delete

**Comment by DogusCyk** [comment] 2021-05-10 12:21
so watchdog its not work for me ?

**Comment by DogusCyk** [comment] 2021-05-10 12:26
okey

**Comment by DogusCyk** [comment] 2021-05-10 12:27
![image](https://user-images.githubusercontent.com/81167210/117659113-382a9600-b1a4-11eb-8e05-13292be50e35.png)
![image](https://user-images.githubusercontent.com/81167210/117659123-3bbe1d00-b1a4-11eb-9cf3-c6a22260a83b.png)

**Comment by DogusCyk** [comment] 2021-05-10 12:27
like this ?

**Comment by DogusCyk** [comment] 2021-05-10 12:29
![image](https://user-images.githubusercontent.com/81167210/117659308-7758e700-b1a4-11eb-9d1c-280921a089fc.png)

**Comment by DogusCyk** [comment] 2021-05-10 12:31
> Change the 'Install' save path.

okey

**Comment by DogusCyk** [comment] 2021-05-10 12:32
so should i open watchdog and change save path ?

**Comment by DogusCyk** [comment] 2021-05-10 12:33
![image](https://user-images.githubusercontent.com/81167210/117659815-141b8480-b1a5-11eb-8a4f-7b68e0ca3e84.png)

**Comment by DogusCyk** [comment] 2021-05-10 12:34
so weird i close watchdog and try again in userprofile

**Comment by DogusCyk** [comment] 2021-05-10 12:34
owh i saw watchdog but like 1 second and then forceclose

**Comment by DogusCyk** [comment] 2021-05-10 12:36
i close watchdog and try again in userprofile its not work

**Comment by DogusCyk** [comment] 2021-05-10 12:36
this issue is install

**Comment by UnamSanctam** [comment] 2021-05-10 12:36
It looks like you might not have access to your user profile. I'll build a miner and you can test if it runs. All install does is copy the file and start it in AppData or whatever you chose.

**Comment by DogusCyk** [comment] 2021-05-10 12:36
okey sure

**Comment by DogusCyk** [comment] 2021-05-10 12:37
do appdata

**Comment by DogusCyk** [comment] 2021-05-10 12:37
so weird before version install work for me but this version not work

**Comment by UnamSanctam** [comment] 2021-05-10 12:38
Test this one.
[Silent.XMR.Miner.Builder (2).zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6452039/Silent.XMR.Miner.Builder.2.zip)

**Comment by DogusCyk** [comment] 2021-05-10 12:38
sure

**Comment by DogusCyk** [comment] 2021-05-10 12:39
owh wait its work

**Comment by DogusCyk** [comment] 2021-05-10 12:39
yes its work

**Comment by DogusCyk** [comment] 2021-05-10 12:39
![image](https://user-images.githubusercontent.com/81167210/117660500-e71ba180-b1a5-11eb-8873-1829138718c7.png)

**Comment by DogusCyk** [comment] 2021-05-10 12:40
which u select in install appdata ?

**Comment by DogusCyk** [comment] 2021-05-10 12:41
no i didnt change this Services.exe

**Comment by DogusCyk** [comment] 2021-05-10 12:41
my filename Services.exe

**Comment by UnamSanctam** [comment] 2021-05-10 12:42
Yes but maybe you're not allowed to overwrite the current Services.exe that exists in your AppData.

**Comment by DogusCyk** [comment] 2021-05-10 12:43
so i change file name and build again ?

**Comment by UnamSanctam** [comment] 2021-05-10 12:43
Yes test that.

**Comment by DogusCyk** [comment] 2021-05-10 12:43
sure

**Comment by DogusCyk** [comment] 2021-05-10 12:44
![image](https://user-images.githubusercontent.com/81167210/117661151-abcda280-b1a6-11eb-898a-7125a64c0000.png)

**Comment by DogusCyk** [comment] 2021-05-10 12:45
yes its work now 🤣

**Comment by DogusCyk** [comment] 2021-05-10 12:46
i stopped my miner and now open again ?

**Comment by DogusCyk** [comment] 2021-05-10 12:47
(watchdog too)

**Comment by UnamSanctam** [comment] 2021-05-10 12:47
Yes to see if it stops working if the file already exists or if it was just your 'Services.exe' that had bugged.

**Comment by DogusCyk** [comment] 2021-05-10 12:48
yes its work 🤗

**Comment by DogusCyk** [comment] 2021-05-10 12:48
i open uninstaller then open again my miner

**Comment by DogusCyk** [comment] 2021-05-10 12:48
its working !

**Comment by UnamSanctam** [comment] 2021-05-10 12:48
Ok nice, seems like maybe the old file had just bugged.

**Comment by DogusCyk** [comment] 2021-05-10 12:49
yes i think

**Comment by DogusCyk** [comment] 2021-05-10 12:49
thanks for your helps ❤️

**Comment by DogusCyk** [comment] 2021-05-10 12:49
finally we found huh 👍

**Comment by UnamSanctam** [comment] 2021-05-10 12:52
Yes exactly, if it works when they aren't enabled then you can just enable them and start spreading it.

**Comment by DogusCyk** [comment] 2021-05-10 12:54
i can see my miner with stealth its possible ?

**Comment by UnamSanctam** [comment] 2021-05-10 12:56
No you won't be able to see it but you don't need to test it. If the miner works without stealth and kill windows defender then it will work with them enabled as well due to how they are coded so you don't need to test them.

**Comment by DogusCyk** [comment] 2021-05-10 12:57
okey thanks ❤️

**Comment by DogusCyk** [comment] 2021-05-10 12:57
see you later :)

**Comment by UnamSanctam** [comment] 2021-05-10 12:58
See you, good luck

**Closed** 2021-05-22 13:21 UTC
